base: 'https://api.typo3.ddev.site/'
dependencies:
  - friendsoftypo3/headless
frontendBase: 'https://typo3.ddev.site:3000/'
headless: 1
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: ''
